org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true

android.useAndroidX=true
android.enableJetifier=true

kotlin.version=1.9.22
kotlin.code.style=official

compileSdk=34
minSdk=28
targetSdk=34

coroutines.version=1.7.3
lifecycle.version=2.7.0
room.version=2.6.1
datastore.version=1.0.0
work.version=2.9.0
material.version=1.11.0
activity.version=1.8.2
fragment.version=1.6.2
navigation.version=2.7.6
protobuf.version=3.24.3
timber.version=5.0.1